# Generated by Django 5.2.9 on 2025-12-06 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('tech_stack', models.CharField(blank=True, max_length=200, verbose_name='Технологии')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
            ],
        ),
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(unique=True, verbose_name='ID Telegram')),
                ('username', models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя пользователя')),
                ('notify_daily', models.BooleanField(default=True, verbose_name='Присылать ежедневно')),
                ('notify_time', models.TimeField(default='06:00', verbose_name='Время уведомления')),
            ],
        ),
    ]
