# Generated by Django 5.2.9 on 2025-12-07 11:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramuser',
            name='notify_daily',
        ),
        migrations.RemoveField(
            model_name='telegramuser',
            name='notify_time',
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='notify_before_lesson',
            field=models.IntegerField(default=15, verbose_name='Уведомлять за (минут)'),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='notify_homework',
            field=models.BooleanField(default=True, verbose_name='Уведомлять о домашке'),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='top_login',
            field=models.CharField(blank=True, max_length=100, verbose_name='Логин Top Academy'),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='top_password_encrypted',
            field=models.TextField(blank=True, verbose_name='Пароль (encrypted)'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='telegram_id',
            field=models.BigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='ManualHomework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200, verbose_name='Предмет')),
                ('task', models.TextField(verbose_name='Задание')),
                ('due_date', models.DateTimeField(verbose_name='Срок сдачи')),
                ('is_done', models.BooleanField(default=False, verbose_name='Выполнено')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeworks', to='tracker.telegramuser')),
            ],
            options={
                'ordering': ['due_date'],
            },
        ),
        migrations.CreateModel(
            name='ManualLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200, verbose_name='Предмет')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Понедельник'), (1, 'Вторник'), (2, 'Среда'), (3, 'Четверг'), (4, 'Пятница'), (5, 'Суббота'), (6, 'Воскресенье')], verbose_name='День недели')),
                ('start_time', models.TimeField(verbose_name='Начало')),
                ('end_time', models.TimeField(verbose_name='Окончание')),
                ('classroom', models.CharField(blank=True, max_length=50, verbose_name='Аудитория')),
                ('teacher', models.CharField(blank=True, max_length=100, verbose_name='Преподаватель')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='tracker.telegramuser')),
            ],
            options={
                'ordering': ['day_of_week', 'start_time'],
            },
        ),
    ]
