# Generated by Django 5.2.9 on 2025-12-08 03:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_remove_telegramuser_notify_daily_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParsedRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Аудитория')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Аудитория (парсинг)',
                'verbose_name_plural': 'Аудитории (парсинг)',
            },
        ),
        migrations.CreateModel(
            name='ParsedSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Название предмета')),
                ('short_name', models.CharField(blank=True, max_length=50, verbose_name='Сокращение')),
            ],
            options={
                'verbose_name': 'Предмет (парсинг)',
                'verbose_name_plural': 'Предметы (парсинг)',
            },
        ),
        migrations.CreateModel(
            name='ParsedTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='ФИО преподавателя')),
                ('short_name', models.CharField(blank=True, max_length=100, verbose_name='Короткое имя')),
            ],
            options={
                'verbose_name': 'Преподаватель (парсинг)',
                'verbose_name_plural': 'Преподаватели (парсинг)',
            },
        ),
        migrations.CreateModel(
            name='UserAuthToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_token', models.TextField(blank=True, verbose_name='Токен авторизации')),
                ('token_expires', models.DateTimeField(blank=True, null=True, verbose_name='Истекает')),
                ('top_login', models.CharField(blank=True, max_length=100, verbose_name='Логин')),
                ('top_password_encrypted', models.TextField(blank=True, verbose_name='Пароль (зашифрован)')),
                ('auto_sync', models.BooleanField(default=True, verbose_name='Автосинхронизация')),
                ('sync_frequency', models.IntegerField(default=24, verbose_name='Частота синхронизации (часов)')),
                ('last_sync_success', models.BooleanField(default=False, verbose_name='Последняя синхр. успешна')),
                ('last_sync_error', models.TextField(blank=True, verbose_name='Последняя ошибка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auth_token', to='tracker.telegramuser')),
            ],
            options={
                'verbose_name': 'Токен пользователя',
                'verbose_name_plural': 'Токены пользователей',
            },
        ),
        migrations.CreateModel(
            name='UserScheduleToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_token', models.TextField(blank=True, verbose_name='Токен авторизации Top Academy')),
                ('auto_sync', models.BooleanField(default=True, verbose_name='Автосинхронизация')),
                ('last_sync', models.DateTimeField(blank=True, null=True, verbose_name='Последняя синхронизация')),
                ('sync_success', models.BooleanField(default=False, verbose_name='Успешная синхронизация')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_token', to='tracker.telegramuser')),
            ],
            options={
                'verbose_name': 'Токен расписания',
                'verbose_name_plural': 'Токены расписания',
            },
        ),
        migrations.CreateModel(
            name='ParsedLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('lesson_number', models.IntegerField(verbose_name='Номер урока')),
                ('started_at', models.TimeField(verbose_name='Начало')),
                ('finished_at', models.TimeField(verbose_name='Окончание')),
                ('is_cancelled', models.BooleanField(default=False, verbose_name='Отменен')),
                ('is_remote', models.BooleanField(default=False, verbose_name='Дистант')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('last_sync', models.DateTimeField(auto_now=True, verbose_name='Последняя синхронизация')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parsed_lessons', to='tracker.telegramuser')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tracker.parsedroom', verbose_name='Аудитория')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tracker.parsedsubject', verbose_name='Предмет')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tracker.parsedteacher', verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name': 'Урок (парсинг)',
                'verbose_name_plural': 'Уроки (парсинг)',
                'ordering': ['date', 'lesson_number'],
                'indexes': [models.Index(fields=['user', 'date'], name='tracker_par_user_id_73a35a_idx'), models.Index(fields=['date'], name='tracker_par_date_d04d50_idx'), models.Index(fields=['user', 'is_cancelled'], name='tracker_par_user_id_666ae1_idx')],
                'unique_together': {('user', 'date', 'lesson_number', 'subject')},
            },
        ),
    ]
