# Generated by Django 5.2.9 on 2025-12-08 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_parsedroom_parsedsubject_parsedteacher_userauthtoken_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userscheduletoken',
            name='user',
        ),
        migrations.RemoveField(
            model_name='telegramuser',
            name='top_login',
        ),
        migrations.RemoveField(
            model_name='telegramuser',
            name='top_password_encrypted',
        ),
        migrations.CreateModel(
            name='UserCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_login', models.TextField(blank=True, verbose_name='Логин (шифр)')),
                ('encrypted_password', models.TextField(blank=True, verbose_name='Пароль (шифр)')),
                ('auth_token', models.TextField(blank=True, verbose_name='Токен авторизации')),
                ('token_expires', models.DateTimeField(blank=True, null=True, verbose_name='Истекает')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='Последний вход')),
                ('login_attempts', models.IntegerField(default=0, verbose_name='Попыток входа')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='tracker.telegramuser')),
            ],
            options={
                'verbose_name': 'Данные входа пользователя',
                'verbose_name_plural': 'Данные входа пользователей',
            },
        ),
        migrations.DeleteModel(
            name='UserAuthToken',
        ),
        migrations.DeleteModel(
            name='UserScheduleToken',
        ),
    ]
